export enum AttributeOptionUiBehavior
{
    PATIENT_DISPOSITION_IS_PENDING = 'PATIENT_DISPOSITION_IS_PENDING',
    PATIENT_DISPOSITION_IS_RELEASED = 'PATIENT_DISPOSITION_IS_RELEASED',
    PATIENT_DISPOSITION_IS_TRANSFERRED = 'PATIENT_DISPOSITION_IS_TRANSFERRED',
    PATIENT_DISPOSITION_IS_DOA = 'PATIENT_DISPOSITION_IS_DOA',
    PATIENT_DISPOSITION_IS_DIED = 'PATIENT_DISPOSITION_IS_DIED',
    PATIENT_DISPOSITION_IS_EUTHANIZED = 'PATIENT_DISPOSITION_IS_EUTHANIZED',

    EXAM_TYPE_IS_FIELD = 'EXAM_TYPE_IS_FIELD',
    EXAM_TYPE_IS_INTAKE = 'EXAM_TYPE_IS_INTAKE',
    EXAM_TYPE_IS_DAILY = 'EXAM_TYPE_IS_DAILY',
    EXAM_TYPE_IS_RELEASE = 'EXAM_TYPE_IS_RELEASE',
    EXAM_BODY_PART_FINDING_IS_ABNORMAL = 'EXAM_BODY_PART_FINDING_IS_ABNORMAL',
}
