export enum Extension
{
    ATTACHMENTS = 'ATTACHMENTS',
    BANDING_MORPHOMETRICS = 'BANDING_MORPHOMETRICS',
    CALCULATORS = 'CALCULATORS',
    CUSTOM_FIELD = 'CUSTOM_FIELD',
    DAILY_EXAM = 'DAILY_EXAM',
    EXPENSES = 'EXPENSES',
    LAB_REPORTS = 'LAB_REPORTS',
    NECROPSY = 'NECROPSY',
    PAPER_FORMS = 'PAPER_FORMS',
    QUICK_ADMIT = 'QUICK_ADMIT',
    OIL_SPILL = 'OIL_SPILL',
}
