export enum SettingKey
{
    TIMEZONE = 'TIMEZONE',
    LANGUAGE = 'LANGUAGE',

    FULL_PEOPLE_ACCESS = 'FULL_PEOPLE_ACCESS',
    REMOTE_RESTRICTED = 'REMOTE_RESTRICTED',
    CLINIC_IP = 'CLINIC_IP',
    USER_REMOTE_PERMISSION = 'USER_REMOTE_PERMISSION',
    ROLE_REMOTE_PERMISSION = 'ROLE_REMOTE_PERMISSION',
    REQUIRE_TWO_FACTOR = 'REQUIRE_TWO_FACTOR',

    LOG_ORDER = 'LOG_ORDER',
    LOG_ALLOW_AUTHOR_EDIT = 'LOG_ALLOW_AUTHOR_EDIT',
    LOG_ALLOW_EDIT = 'LOG_ALLOW_EDIT',
    LOG_ALLOW_DELETE = 'LOG_ALLOW_DELETE',
    LOG_SHARES = 'LOG_SHARES',

    SHOW_LOOKUP_RESCUER = 'SHOW_LOOKUP_RESCUER',
    SHOW_GEOLOCATION_FIELDS = 'SHOW_GEOLOCATION_FIELDS',
    AREAS = 'AREAS',
    ENCLOSURES = 'ENCLOSURES',
    LISTED_FIELDS = 'LISTED_FIELDS',

    SHOW_TAGS = 'SHOW_TAGS',
    WILD_ALERT_SHARING = 'WILD_ALERT_SHARING',
    EXPORT_SHARING = 'EXPORT_SHARING',
}
