<?php

namespace App\Enums;

enum AttributeOptionUiBehavior: string
{
    case DONATION_METHOD_IS_CASH = 'DONATION_METHOD_IS_CASH';

    case PATIENT_DISPOSITION_IS_PENDING = 'PATIENT_DISPOSITION_IS_PENDING';
    case PATIENT_DISPOSITION_IS_RELEASED = 'PATIENT_DISPOSITION_IS_RELEASED';
    case PATIENT_DISPOSITION_IS_TRANSFERRED = 'PATIENT_DISPOSITION_IS_TRANSFERRED';
    case PATIENT_DISPOSITION_IS_DOA = 'PATIENT_DISPOSITION_IS_DOA';
    case PATIENT_DISPOSITION_IS_DIED = 'PATIENT_DISPOSITION_IS_DIED';
    case PATIENT_DISPOSITION_IS_EUTHANIZED = 'PATIENT_DISPOSITION_IS_EUTHANIZED';
    case PATIENT_DISPOSITION_IS_DEAD = 'PATIENT_DISPOSITION_IS_DEAD';

    case EXAM_TYPE_IS_FIELD = 'EXAM_TYPE_IS_FIELD';
    case EXAM_TYPE_IS_INTAKE = 'EXAM_TYPE_IS_INTAKE';
    case EXAM_TYPE_IS_DAILY = 'EXAM_TYPE_IS_DAILY';
    case EXAM_TYPE_IS_RELEASE = 'EXAM_TYPE_IS_RELEASE';
    case EXAM_TYPE_CAN_ONLY_OCCUR_ONCE = 'EXAM_TYPE_CAN_ONLY_OCCUR_ONCE';
    case EXAM_AGE_IS_MATURE = 'EXAM_AGE_IS_MATURE';
    case EXAM_WEIGHT_UNITS_IS_KG = 'EXAM_WEIGHT_UNITS_IS_KG';
    case EXAM_WEIGHT_UNITS_IS_G = 'EXAM_WEIGHT_UNITS_IS_G';
    case EXAM_WEIGHT_UNITS_IS_LB = 'EXAM_WEIGHT_UNITS_IS_LB';
    case EXAM_WEIGHT_UNITS_IS_OZ = 'EXAM_WEIGHT_UNITS_IS_OZ';
    case EXAM_WEIGHT_TEMPERATURE_IS_C = 'EXAM_WEIGHT_TEMPERATURE_IS_C';
    case EXAM_WEIGHT_TEMPERATURE_IS_F = 'EXAM_WEIGHT_TEMPERATURE_IS_F';
    case EXAM_WEIGHT_TEMPERATURE_IS_K = 'EXAM_WEIGHT_TEMPERATURE_IS_K';
    case EXAM_BODY_PART_FINDING_IS_ABNORMAL = 'EXAM_BODY_PART_FINDING_IS_ABNORMAL';

    case PATIENT_LOCATION_FACILITIES_IS_CLINIC = 'PATIENT_LOCATION_FACILITIES_IS_CLINIC';
    case PATIENT_LOCATION_FACILITIES_IS_OFF_SITE = 'PATIENT_LOCATION_FACILITIES_IS_OFF_SITE';
    case PATIENT_LOCATION_FACILITIES_IS_HOMECARE = 'PATIENT_LOCATION_FACILITIES_IS_HOMECARE';

    case DAILY_TASK_FREQUENCY_IS_SINGLE_DOSE = 'DAILY_TASK_FREQUENCY_IS_SINGLE_DOSE';
    case DAILY_TASK_FREQUENCY_IS_EVERY_2_DAYS = 'DAILY_TASK_FREQUENCY_IS_EVERY_2_DAYS';
    case DAILY_TASK_FREQUENCY_IS_EVERY_3_DAYS = 'DAILY_TASK_FREQUENCY_IS_EVERY_3_DAYS';
    case DAILY_TASK_FREQUENCY_IS_EVERY_4_DAYS = 'DAILY_TASK_FREQUENCY_IS_EVERY_4_DAYS';
    case DAILY_TASK_FREQUENCY_IS_EVERY_5_DAYS = 'DAILY_TASK_FREQUENCY_IS_EVERY_5_DAYS';
    case DAILY_TASK_FREQUENCY_IS_EVERY_7_DAYS = 'DAILY_TASK_FREQUENCY_IS_EVERY_7_DAYS';
    case DAILY_TASK_FREQUENCY_IS_EVERY_14_DAYS = 'DAILY_TASK_FREQUENCY_IS_EVERY_14_DAYS';
    case DAILY_TASK_FREQUENCY_IS_EVERY_21_DAYS = 'DAILY_TASK_FREQUENCY_IS_EVERY_21_DAYS';
    case DAILY_TASK_FREQUENCY_IS_EVERY_28_DAYS = 'DAILY_TASK_FREQUENCY_IS_EVERY_28_DAYS';
    case DAILY_TASK_FREQUENCY_IS_SCATTERED_DAYS = 'DAILY_TASK_FREQUENCY_IS_SCATTERED_DAYS';
    case DAILY_TASK_FREQUENCY_IS_2_DAILY = 'DAILY_TASK_FREQUENCY_IS_2_DAILY';
    case DAILY_TASK_FREQUENCY_IS_3_DAILY = 'DAILY_TASK_FREQUENCY_IS_3_DAILY';
    case DAILY_TASK_FREQUENCY_IS_4_DAILY = 'DAILY_TASK_FREQUENCY_IS_4_DAILY';
    case DAILY_TASK_FREQUENCY_IS_5_DAILY = 'DAILY_TASK_FREQUENCY_IS_5_DAILY';
    case DAILY_TASK_FREQUENCY_IS_6_DAILY = 'DAILY_TASK_FREQUENCY_IS_6_DAILY';
    case DAILY_TASK_ASSIGNMENT_IS_VETERINARIAN = 'DAILY_TASK_ASSIGNMENT_IS_VETERINARIAN';
    case DAILY_TASK_CONCENTRATION_UNIT_IS_MG_PER_ML = 'DAILY_TASK_CONCENTRATION_UNIT_IS_MG_PER_ML';
    case DAILY_TASK_CONCENTRATION_UNIT_IS_MG_PER_TAB = 'DAILY_TASK_CONCENTRATION_UNIT_IS_MG_PER_TAB';
    case DAILY_TASK_CONCENTRATION_UNIT_IS_MG_PER_CAP = 'DAILY_TASK_CONCENTRATION_UNIT_IS_MG_PER_CAP';
    case DAILY_TASK_CONCENTRATION_UNIT_IS_MG_PER_GRAM = 'DAILY_TASK_CONCENTRATION_UNIT_IS_MG_PER_GRAM';
    case DAILY_TASK_CONCENTRATION_UNIT_IS_IU_PER_CAP = 'DAILY_TASK_CONCENTRATION_UNIT_IS_IU_PER_CAP';
    case DAILY_TASK_CONCENTRATION_UNIT_IS_IU_PER_ML = 'DAILY_TASK_CONCENTRATION_UNIT_IS_IU_PER_ML';
    case DAILY_TASK_CONCENTRATION_UNIT_IS_MG = 'DAILY_TASK_CONCENTRATION_UNIT_IS_MG';
    case DAILY_TASK_CONCENTRATION_UNIT_IS_IU = 'DAILY_TASK_CONCENTRATION_UNIT_IS_IU';
    case DAILY_TASK_DOSAGE_UNIT_IS_MG_PER_KG = 'DAILY_TASK_DOSAGE_UNIT_IS_MG_PER_KG';
    case DAILY_TASK_DOSAGE_UNIT_IS_IU_PER_KG = 'DAILY_TASK_DOSAGE_UNIT_IS_IU_PER_KG';
    case DAILY_TASK_DOSAGE_UNIT_IS_MG_PER_LB = 'DAILY_TASK_DOSAGE_UNIT_IS_MG_PER_LB';
    case DAILY_TASK_DOSAGE_UNIT_IS_IU_PER_LB = 'DAILY_TASK_DOSAGE_UNIT_IS_IU_PER_LB';
    case DAILY_TASK_DOSAGE_UNIT_IS_PER_KG = 'DAILY_TASK_DOSAGE_UNIT_IS_PER_KG';
    case DAILY_TASK_DOSAGE_UNIT_IS_PER_LB = 'DAILY_TASK_DOSAGE_UNIT_IS_PER_LB';
    case DAILY_TASK_DOSE_UNIT_IS_ML = 'DAILY_TASK_DOSE_UNIT_IS_ML';
    case DAILY_TASK_DOSE_UNIT_IS_CAP = 'DAILY_TASK_DOSE_UNIT_IS_CAP';
    case DAILY_TASK_DOSE_UNIT_IS_TAB = 'DAILY_TASK_DOSE_UNIT_IS_TAB';
    case DAILY_TASK_DOSE_UNIT_IS_GRAM = 'DAILY_TASK_DOSE_UNIT_IS_GRAM';
    case DAILY_TASK_NUTRITION_FREQUENCY_IS_HOURS = 'DAILY_TASK_NUTRITION_FREQUENCY_IS_HOURS';

    case HOTLINE_STATUS_IS_OPEN = 'HOTLINE_STATUS_IS_OPEN';
    case HOTLINE_STATUS_IS_UNRESOLVED = 'HOTLINE_STATUS_IS_UNRESOLVED';
    case HOTLINE_STATUS_IS_RESOLVED = 'HOTLINE_STATUS_IS_RESOLVED';

    case NECROPSY_SAMPLES_IS_OTHER = 'NECROPSY_SAMPLES_IS_OTHER';

    case OILED_PROCESSING_CONDITION_IS_ALIVE = 'OILED_PROCESSING_CONDITION_IS_ALIVE';
    case OILED_PROCESSING_CONDITION_IS_DEAD = 'OILED_PROCESSING_CONDITION_IS_DEAD';
    case OILED_WASH_PRE_TREATMENT_IS_NONE = 'OILED_WASH_PRE_TREATMENT_IS_NONE';
    case OILED_WASH_TYPE_IS_INITIAL = 'OILED_WASH_TYPE_IS_INITIAL';
}
