<?php

namespace App\Enums;

enum AttributeOptionName: string
{
    case TAXA_MORPHS = 'TAXA_MORPHS';
    case TAXA_CLASSES = 'TAXA_CLASSES';

    case HOTLINE_WILDLIFE_CATEGORIES = 'HOTLINE_WILDLIFE_CATEGORIES';
    case HOTLINE_ADMINISTRATIVE_CATEGORIES = 'HOTLINE_ADMINISTRATIVE_CATEGORIES';
    case HOTLINE_OTHER_CATEGORIES = 'HOTLINE_OTHER_CATEGORIES';
    case HOTLINE_STATUSES = 'HOTLINE_STATUSES';

    case PATIENT_DISPOSITIONS = 'PATIENT_DISPOSITIONS';
    case PATIENT_RELEASE_TYPES = 'PATIENT_RELEASE_TYPES';
    case PATIENT_TRANSFER_TYPES = 'PATIENT_TRANSFER_TYPES';
    case PATIENT_LOCATION_FACILITIES = 'PATIENT_LOCATION_FACILITIES';

    case EXAM_TYPES = 'EXAM_TYPES';
    case EXAM_AVES_AGE_UNITS = 'EXAM_AVES_AGE_UNITS';
    case EXAM_MAMMALIA_AGE_UNITS = 'EXAM_MAMMALIA_AGE_UNITS';
    case EXAM_AMPHIBIA_AGE_UNITS = 'EXAM_AMPHIBIA_AGE_UNITS';
    case EXAM_REPTILIA_AGE_UNITS = 'EXAM_REPTILIA_AGE_UNITS';
    case EXAM_CHRONOLOGICAL_AGE_UNITS = 'EXAM_CHRONOLOGICAL_AGE_UNITS';
    case EXAM_DEHYDRATIONS = 'EXAM_DEHYDRATIONS';
    case EXAM_WEIGHT_UNITS = 'EXAM_WEIGHT_UNITS';
    case EXAM_TEMPERATURE_UNITS = 'EXAM_TEMPERATURE_UNITS';
    case EXAM_MUCUS_MEMBRANE_COLORS = 'EXAM_MUCUS_MEMBRANE_COLORS';
    case EXAM_MUCUS_MEMBRANE_TEXTURES = 'EXAM_MUCUS_MEMBRANE_TEXTURES';
    case EXAM_SEXES = 'EXAM_SEXES';
    case EXAM_BODY_CONDITIONS = 'EXAM_BODY_CONDITIONS';
    case EXAM_ATTITUDES = 'EXAM_ATTITUDES';
    case EXAM_BODY_PART_FINDINGS = 'EXAM_BODY_PART_FINDINGS';

    case PERSON_ENTITY_TYPES = 'PERSON_ENTITY_TYPES';
    case DONATION_METHODS = 'DONATION_METHODS';

    case DAILY_TASK_ASSIGNMENTS = 'DAILY_TASK_ASSIGNMENTS';
    case DAILY_TASK_FREQUENCIES = 'DAILY_TASK_FREQUENCIES';
    case DAILY_TASK_CONCENTRATION_UNITS = 'DAILY_TASK_CONCENTRATION_UNITS';
    case DAILY_TASK_DOSAGE_UNITS = 'DAILY_TASK_DOSAGE_UNITS';
    case DAILY_TASK_DOSE_UNITS = 'DAILY_TASK_DOSE_UNITS';
    case DAILY_TASK_ROUTES = 'DAILY_TASK_ROUTES';
    case DAILY_TASK_NUTRITION_ROUTES = 'DAILY_TASK_NUTRITION_ROUTES';

    case NECROPSY_CARCASS_CONDITIONS = 'NECROPSY_CARCASS_CONDITIONS';
    case NECROPSY_SAMPLES = 'NECROPSY_SAMPLES';

    case BANDING_AGE_CODES = 'BANDING_AGE_CODES';
    case BANDING_HOW_AGED_CODES = 'BANDING_HOW_AGED_CODES';
    case BANDING_SEX_CODES = 'BANDING_SEX_CODES';
    case BANDING_HOW_SEXED_CODES = 'BANDING_HOW_SEXED_CODES';
    case BANDING_STATUS_CODES = 'BANDING_STATUS_CODES';
    case BANDING_ADDITIONAL_INFORMATION_STATUS_CODES = 'BANDING_ADDITIONAL_INFORMATION_STATUS_CODES';
    case BANDING_DISPOSITION_CODES = 'BANDING_DISPOSITION_CODES';
    case BANDING_RECAPTURE_DISPOSITION_CODES = 'BANDING_RECAPTURE_DISPOSITION_CODES';
    case BANDING_PRESENT_CONDITION_CODES = 'BANDING_PRESENT_CONDITION_CODES';
    case BANDING_HOW_PRESENT_CONDITION_CODES = 'BANDING_HOW_PRESENT_CONDITION_CODES';
    case BANDING_BAND_SIZES = 'BANDING_BAND_SIZES';
    case BANDING_SAMPLES_COLLECTED = 'BANDING_SAMPLES_COLLECTED';
    case BANDING_AUXILLARY_MARKER_TYPE_CODES = 'BANDING_AUXILLARY_MARKER_TYPE_CODES';
    case BANDING_AUXILLARY_COLOR_CODES = 'BANDING_AUXILLARY_COLOR_CODES';
    case BANDING_AUXILLARY_CODE_COLOR = 'BANDING_AUXILLARY_CODE_COLOR';
    case BANDING_AUXILLARY_SIDE_OF_BIRD = 'BANDING_AUXILLARY_SIDE_OF_BIRD';
    case BANDING_PLACEMENT_ON_LEG = 'BANDING_PLACEMENT_ON_LEG';

    case OILED_PROCESSING_CONDITIONS = 'OILED_PROCESSING_CONDITIONS';
    case OILED_PROCESSING_STATUSES = 'OILED_PROCESSING_STATUSES';
    case OILED_PROCESSING_OILING_PERCENTAGES = 'OILED_PROCESSING_OILING_PERCENTAGES';
    case OILED_PROCESSING_OILING_DEPTHS = 'OILED_PROCESSING_OILING_DEPTHS';
    case OILED_PROCESSING_OILING_LOCATIONS = 'OILED_PROCESSING_OILING_LOCATIONS';
    case OILED_PROCESSING_EVIDENCES = 'OILED_PROCESSING_EVIDENCES';
    case OILED_PROCESSING_CARCASS_CONDITIONS = 'OILED_PROCESSING_CARCASS_CONDITIONS';
    case OILED_PROCESSING_EXTENT_OF_SCAVENGINGS = 'OILED_PROCESSING_EXTENT_OF_SCAVENGINGS';
    case OILED_PROCESSING_OIL_CONDITION = 'OILED_PROCESSING_OIL_CONDITION';
    case OILED_PROCESSING_OIL_TYPES = 'OILED_PROCESSING_OIL_TYPES';
}
