<?php

namespace App\Enums;

enum AttributeOptionName: string
{
    case TAXA_MORPHS = 'TAXA_MORPHS';
    case TAXA_CLASSES = 'TAXA_CLASSES';

    case HOTLINE_WILDLIFE_CATEGORIES = 'HOTLINE_WILDLIFE_CATEGORIES';
    case HOTLINE_ADMINISTRATIVE_CATEGORIES = 'HOTLINE_ADMINISTRATIVE_CATEGORIES';
    case HOTLINE_OTHER_CATEGORIES = 'HOTLINE_OTHER_CATEGORIES';
    case HOTLINE_STATUSES = 'HOTLINE_STATUSES';

    case PATIENT_DISPOSITIONS = 'PATIENT_DISPOSITIONS';
    case PATIENT_RELEASE_TYPES = 'PATIENT_RELEASE_TYPES';
    case PATIENT_TRANSFER_TYPES = 'PATIENT_TRANSFER_TYPES';
    case PATIENT_LOCATION_FACILITIES = 'PATIENT_LOCATION_FACILITIES';

    case EXAM_TYPES = 'EXAM_TYPES';
    case EXAM_AVES_AGE_UNITS = 'EXAM_AVES_AGE_UNITS';
    case EXAM_MAMMALIA_AGE_UNITS = 'EXAM_MAMMALIA_AGE_UNITS';
    case EXAM_AMPHIBIA_AGE_UNITS = 'EXAM_AMPHIBIA_AGE_UNITS';
    case EXAM_REPTILIA_AGE_UNITS = 'EXAM_REPTILIA_AGE_UNITS';
    case EXAM_CHRONOLOGICAL_AGE_UNITS = 'EXAM_CHRONOLOGICAL_AGE_UNITS';
    case EXAM_DEHYDRATIONS = 'EXAM_DEHYDRATIONS';
    case EXAM_WEIGHT_UNITS = 'EXAM_WEIGHT_UNITS';
    case EXAM_TEMPERATURE_UNITS = 'EXAM_TEMPERATURE_UNITS';
    case EXAM_MUCUS_MEMBRANE_COLORS = 'EXAM_MUCUS_MEMBRANE_COLORS';
    case EXAM_MUCUS_MEMBRANE_TEXTURES = 'EXAM_MUCUS_MEMBRANE_TEXTURES';
    case EXAM_SEXES = 'EXAM_SEXES';
    case EXAM_BODY_CONDITIONS = 'EXAM_BODY_CONDITIONS';
    case EXAM_ATTITUDES = 'EXAM_ATTITUDES';
    case EXAM_BODY_PART_FINDINGS = 'EXAM_BODY_PART_FINDINGS';

    case PERSON_ENTITY_TYPES = 'PERSON_ENTITY_TYPES';
    case DONATION_METHODS = 'DONATION_METHODS';

    case DAILY_TASK_ASSIGNMENTS = 'DAILY_TASK_ASSIGNMENTS';
    case DAILY_TASK_FREQUENCIES = 'DAILY_TASK_FREQUENCIES';
    case DAILY_TASK_CONCENTRATION_UNITS = 'DAILY_TASK_CONCENTRATION_UNITS';
    case DAILY_TASK_DOSAGE_UNITS = 'DAILY_TASK_DOSAGE_UNITS';
    case DAILY_TASK_DOSE_UNITS = 'DAILY_TASK_DOSE_UNITS';
    case DAILY_TASK_ROUTES = 'DAILY_TASK_ROUTES';
    case DAILY_TASK_NUTRITION_ROUTES = 'DAILY_TASK_NUTRITION_ROUTES';
}
